#!/bin/bash

# Function to get the current network interface name
get_interface_name() {
    echo "Available network interfaces:"
    ip -o link show | awk -F': ' '{print $2}'
    read -p "Enter the network interface name you want to configure: " INTERFACE
}

# Function to back up the current network configuration
backup_config() {
    BACKUP_FILE="/etc/network/interfaces.bak_$(date +%F_%T)"
    echo "Backing up current network configuration to $BACKUP_FILE"
    cp /etc/network/interfaces $BACKUP_FILE
}

# Function to configure static IP
configure_static_ip() {
    read -p "Enter the static IP address: " IP_ADDRESS
    read -p "Enter the netmask (e.g., 255.255.255.0): " NETMASK
    read -p "Enter the gateway: " GATEWAY

    echo "Configuring static IP..."
    cat <<EOL > /etc/network/interfaces
# This file was automatically generated by a script
auto lo
iface lo inet loopback

auto $INTERFACE
iface $INTERFACE inet static
    address $IP_ADDRESS
    netmask $NETMASK
    gateway $GATEWAY
EOL

    echo "Static IP configuration complete. Restarting network services..."
    systemctl restart networking
    echo "Network services restarted."
}

# Main script execution
get_interface_name
backup_config
configure_static_ip

echo "Done."
